services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: strv-addressbook
      POSTGRES_USER: fake-username
      POSTGRES_PASSWORD: fake-password
    ports:
      - 5432:5432
  firestore:
    image: firestore
    build:
      context: .
      dockerfile: firestore.Dockerfile
    ports:
      - 4000:4000
      - 4400:4400
      - 4500:4500
      - 8080:8080